spring:
  application:
    name: OLX-Login
  data:
    mongodb:
      database: BlackListed
      host: localhost
      port: 27017
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/olxlogin
    username: root
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost
    management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411
springdoc:
  show-actuator: TRUE
